### ISSUE TITLE
Issue with parameter settings

### ISSUE THREAD

**Issue by hexavier** [borisz264/ribo_seq#1]
I was interested to run a similar analysis as in [here](https://doi.org/10.1016/j.molcel.2018.12.009), but there seems to be an issue with the settings. When running `ribo_seq_main.py`, the following error appears:
```
Traceback (most recent call last):
  File "ribo_seq_main.py", line 460, in <module>
    main()
  File "ribo_seq_main.py", line 436, in main
    settings = ribo_settings.ribo_settings(args.settings_file)
  File "myPATH/ribo_settings.py", line 13, in __init__
    self.process_settings(settings_file)
  File "myPATH/ribo_settings.py", line 66, in process_settings
    settings[k] = int(settings[k])
KeyError: 'outfiltermismatchnmax'
```
It seems that `ribo_settings.py` requires more parameters than the ones in the json file.

**Comment by borisz264** [comment]
I recommend trying the code and files in https://github.com/borisz264/rRNA_depletion_2020. That code and those files worked on the day I deposited them and have not been changed. I actively modify the code here so sometimes there are issues.
